[[redirects]]
  from = "/apollo/*"
  to = "https://api.apollo.io/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, x-api-key"}

[[redirects]]
  from = "/mails/*"
  to = "https://api.mails.so/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization"}

[build]
  command = "npm run build"
  publish = "dist" 