[[redirects]]
  from = "/apollo/*"
  to = "https://api.apollo.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/mails/*"
  to = "https://api.mails.so/:splat"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist" 